docno="lists-038-14582549"
received="Wed Nov 18 16:50:24 1998"
isoreceived="19981118215024"
sent="Wed, 18 Nov 1998 13:49:13 -0800"
isosent="19981118214913"
name="Alex Hopmann (Exchange)"
email="alexhop@exchange.microsoft.com"
subject="RE: Interoperability of MSIE 5 with PyDAV"
id="E46F2E74BFC4CF119A8B00805FCCAB2705CC2DCC@RENCHOW"
charset="windows-1252"
inreplyto="Interoperability of MSIE 5 with PyDAV"
expires="-1"


To:"'Jim Davis'"<jdavis@parc.xerox.com>,w3c-dist-auth@w3.org

Jim, we are working on testing it out. I'll send some more info to the list
once we find out what the real situation is.

Alex

> -----Original Message-----
> From: Jim Davis [mailto:jdavis@parc.xerox.com]
> Sent: Wednesday, November 18, 1998 1:33 PM
> To: w3c-dist-auth@w3.org
> Subject: Interoperability of MSIE 5 with PyDAV
> 
> 
> This afternoon Jim Whitehead and I tried MSIE 5 with PyDAV.  
> I regret to
> say that it didn't work, and we don't know why.  Perhaps 
> someone from MS
> can shed some light on it.  At present, we can't tell whether it's
> deficiencies in PyDAV, relative misinterpretations, or bugs in MSIE.
> 
> All we know is that MSIE didn't successfully connect.  it did 
> not utter any
> diagnostic or complaint.  on the PyDAV side, we see in the 
> logs that MSIE
> did am OPTIONS, followed by a GET, then a POST, then said 
> nothing else.
> 
> PyDAV does not support POST.
> 
> Note that an earlier version of PyDAV responded to POST with 
> status 500,
> which is not the right way to show that POST is not supported.  It now
> returns 501.
> 
> Here's the log trace.  Note that all the headers are coerced 
> to upper case
> in the log.  Comments in between request/response pairs are mine.
> 
> 1998-11-18 12:58:35 [HTTP] Request OPTIONS / HTTP/1.1
> 1998-11-18 12:58:36 [HTTP] Headers: CONNECTION: Keep-Alive
> HOST: sandbox.xerox.com:8080
> USER-AGENT: Microsoft Data Access Internet Publishing 
> Provider Cache Manager
> 1998-11-18 12:58:36 [Reply] 200
> 
> [Does MSIE inspect either the Public or the Allow header?  
> PyDAV returns
> Allow, but not Public.  I modified it to also return Public, 
> but that did
> not change things any.]
> 
> 1998-11-18 12:58:36 [HTTP] Request GET /_vti_inf.html HTTP/1.1
> 1998-11-18 12:58:36 [HTTP] Headers: CONNECTION: Keep-Alive
> USER-AGENT: Mozilla/2.0 (compatible; MS FrontPage 4.0)
> CONTENT-LENGTH: 0
> HOST: sandbox.xerox.com:8080
> DATE: Wed, 18 Nov 1998 20:57:59 GMT
> ACCEPT: auth/sicily
> MIME-VERSION: 1.0
> 1998-11-18 12:58:36 [HTTP] Complaint 404 Not Found
> 1998-11-18 12:58:36 [Reply] 404 79 bytes
> 
> [Note that the only mime type in ACCEPT is auth/sicily.  As 
> it happens,
> PyDAV ignores the Accept header anyway, but if it did try to 
> obey it, it's
> not clear how it could have returned a resource of type 'auth/sicily'.
> Besides that, what is "sicilian" authorization?  A request 
> you can't say
> "no" to?  :-)]
> 
> 1998-11-18 12:58:36 [HTTP] Request POST 
> /_vti_bin/shtml.exe/_vti_rpc HTTP/1.1
> 1998-11-18 12:58:36 [HTTP] Headers: CONNECTION: Keep-Alive
> USER-AGENT: MSFrontPage/4.0
> CONTENT-LENGTH: 41
> HOST: sandbox.xerox.com:8080
> CONTENT-TYPE: application/x-www-form-urlencoded
> X-VERMEER-CONTENT-TYPE: application/x-www-form-urlencoded
> DATE: Wed, 18 Nov 1998 20:58:00 GMT
> ACCEPT: auth/sicily
> MIME-VERSION: 1.0
> 1998-11-18 12:58:36 [HTTP] Complaint 501
> 
> [PyDAV does not support POST at all.]
> 



