docno="lists-098-10589691"
received="Mon Mar 11 17:29:59 2002"
isoreceived="20020311222959"
sent="11 Mar 2002 16:30:13 -0600"
isosent="20020311223013"
name="Dan Connolly"
email="connolly@w3.org"
subject="validating tr2.rdf crashes cwm"
id="1015885813.5227.182.camel@dirk"
charset="ANSI_X3.4-1968"
expires="-1"

To: Tim Berners-Lee<timbl@w3.org>
Cc: www-archive+n3bugs@w3.org


command line:

$ python ../cwm.py --chatty=20 validate.n3 --think --with 
http://www.w3.org/2000/04/mem-news/tr2.rdf >,valout.n3 2>,errs &

version info:

$ ident cwm.py llyn.py
cwm.py:
     $Id: cwm.py,v 1.90 2002/03/08 04:05:05 timbl Exp $
     $Revision: 1.90 $
     $Id: cwm.py,v 1.90 2002/03/08 04:05:05 timbl Exp $

llyn.py:
     $Id: llyn.py,v 1.18 2002/03/08 18:54:01 timbl Exp $
     $Revision: 1.18 $



backtrace etc. attached

short version:
  File "../llyn.py", line 1908, in conclude
    poss = conclusion.universals()
AttributeError: Fragment instance has no attribute 'universals'

-- 
Dan Connolly, W3C http://www.w3.org/People/Connolly/


Total 1 new statements from rules in 0_work 
Reading and parsing /www.w3.org/2000/04/mem-news/tr2.rdf 
    semantics: http://www.w3.org/2000/04/mem-news/tr2.rdf#_formula 
Reading and parsing /www.w3.org/2001/02pd/rec54 
    semantics: http://www.w3.org/2001/02pd/rec54#_formula 
Already read and parsed /www.w3.org/2001/02pd/rec54 to _formula 
Reading and parsing home/connolly/w3ccvs/WWW/2000/10/swap-cur/util/schema-rules.n3 
    semantics: file:/home/connolly/w3ccvs/WWW/2000/10/swap-cur/util/schema-rules.n3#_formula 
Bultin: _gs19 log:conclusion None 
Traceback (most recent call last):
  File "../cwm.py", line 625, in ?
    doCommand()
  File "../cwm.py", line 577, in doCommand
    _store.think(workingContext)
  File "../llyn.py", line 1501, in think
    step = self.applyRules(F, F, alreadyDictionary=bindingsFound)
  File "../llyn.py", line 1547, in applyRules
    already=already)
  File "../llyn.py", line 1600, in tryRule
    ( self, conclusion, targetContext,  # _outputVariables,
  File "../llyn.py", line 1885, in match
    bindings=[], justOne=justOne)
  File "../llyn.py", line 2098, in query2
    bindings[:], nb, justOne=justOne, level=level+2)
  File "../llyn.py", line 2098, in query2
    bindings[:], nb, justOne=justOne, level=level+2)
  File "../llyn.py", line 2098, in query2
    bindings[:], nb, justOne=justOne, level=level+2)
  File "../llyn.py", line 2098, in query2
    bindings[:], nb, justOne=justOne, level=level+2)
  File "../llyn.py", line 2074, in query2
    nbs = item.tryHeavy(queue, bindings)
  File "../llyn.py", line 2291, in tryHeavy
    result = pred.evaluateObject2(subj)
  File "../llyn.py", line 598, in evaluateObject2
    store.think(F)
  File "../llyn.py", line 1501, in think
    step = self.applyRules(F, F, alreadyDictionary=bindingsFound)
  File "../llyn.py", line 1547, in applyRules
    already=already)
  File "../llyn.py", line 1600, in tryRule
    ( self, conclusion, targetContext,  # _outputVariables,
  File "../llyn.py", line 1885, in match
    bindings=[], justOne=justOne)
  File "../llyn.py", line 2108, in query2
    return action(bindings, param, level)  # No terms left .. success!
  File "../llyn.py", line 1908, in conclude
    poss = conclusion.universals()
AttributeError: Fragment instance has no attribute 'universals'



