docno="lists-098-2932907"
received="Thu Aug  8 08:20:43 2002"
isoreceived="20020808122043"
sent="Thu, 8 Aug 2002 14:20:11 +0200"
isosent="20020808122011"
name="Jos De_Roo"
email="jos.deroo.jd@belgium.agfa.com"
subject="a traceback while using cwm.py 1.103"
id="OFC7206773.17AD894F-ONC1256C0F.00428773@agfa.be"
charset="us-ascii"
expires="-1"

To:"connolly"<connolly@w3.org>,"timbl"<timbl@w3.org>
Cc:www-archive@w3.org



I was trying to redo (to get more "suffix avoidance")
  http://www.w3.org/2000/10/rdf-tests/rdfcore/testSchema.n3
(as I did last week for
  http://www.w3.org/2002/03owlt/FunctionalProperty/Manifest.n3)

but since cwm.py 1.99 and/or notation3.py 1.112 I get

[[[
Administrator@VAM969 ~/w3ccvs
$ cwm http://www.w3.org/2000/10/rdf-tests/rdfcore/testSchema
#Processed by Id: cwm.py,v 1.103 2002/08/08 02:03:35 timbl Exp
        #    using base 
http://www.w3.org/2000/10/rdf-tests/rdfcore/testSchema
        Traceback (most recent call last):
  File "/w3ccvs/WWW/2000/10/swap/cwm.py", line 615, in ?
    doCommand()
  File "/w3ccvs/WWW/2000/10/swap/cwm.py", line 476, in doCommand
    p.load(_inputURI)
  File "/w3ccvs/WWW/2000/10/swap\notation3.py", line 155, in load
    self.feed(netStream.read())     # @ May be big - buffered in memory!
  File "/w3ccvs/WWW/2000/10/swap\notation3.py", line 176, in feed
    i = self.directiveOrStatement(str,j)
  File "/w3ccvs/WWW/2000/10/swap\notation3.py", line 189, in 
directiveOrStatement
    j = self.statement(str, i)
  File "/w3ccvs/WWW/2000/10/swap\notation3.py", line 269, in statement
    j = self.property_list(str, i, r[0])
  File "/w3ccvs/WWW/2000/10/swap\notation3.py", line 466, in property_list
    i = self.object_list(str, j, objs)
  File "/w3ccvs/WWW/2000/10/swap\notation3.py", line 481, in object_list
    i = self.object(str, i, res)
  File "/w3ccvs/WWW/2000/10/swap\notation3.py", line 623, in object
    j = self.subject(str, i, res)
  File "/w3ccvs/WWW/2000/10/swap\notation3.py", line 276, in subject
    return self.node(str, i, res)
  File "/w3ccvs/WWW/2000/10/swap\notation3.py", line 352, in node
    j = self.uri_ref2(str, i, res)
  File "/w3ccvs/WWW/2000/10/swap\notation3.py", line 521, in uri_ref2
    raise BadSyntax(self._thisDoc, self.lines, str, i, "Prefix %s not 
bound" % (pfx))
notation3.BadSyntax: Line 13 of 
<http://www.w3.org/2000/10/rdf-tests/rdfcore/testSchema>:
Bad syntax (Prefix Description not bound) at ^ in:
"...<http://www.w3.org/Consortium/Legal/copyright-software.html>^

  Description: RDF Schema for test case manifest terms.

 ..."

Administrator@VAM969 ~/w3ccvs
$
]]]

-- ,
Jos De Roo, AGFA http://www.agfa.com/w3c/jdroo/



